version: "3.9"
services:
  primary:
    image: redis
    ports:
      - "6379:6379"
    command: 
      "/usr/local/bin/redis-server --save 60 1 --loglevel debug"
  replica:
    image: redis
    depends_on:
      - primary
    ports:
      - "6380:6379"
    command: 
      "/usr/local/bin/redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - "./conf:/usr/local/etc/redis"
    
