version: "3.9"
services:
  neo4j:  
    image: neo4j
    restart: always
    ports:
      - 8093:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/1q2w3e!
    volumes:      
      - ./../raw:/import