version: "3.9"
services:
  scylla-primary:
    image: scylladb/scylla
    command: ['--smp 1']
    ports:
      - "127.0.0.1:9042:9042"
      - "127.0.0.1:10000:10000"
  scylla-replica:
    image: scylladb/scylla
    command: ['--smp 1', '--seeds=scylla-primary']
